import { View, Text, StyleSheet, FlatList, TouchableOpacity, TextInput } from 'react-native';
import { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { useTwinStore } from '../store/useTwinStore';

export default function Goals() {
  const { userId } = useTwinStore();
    const [goals, setGoals] = useState<any[]>([]);
      const [title, setTitle] = useState('');
        const [desc, setDesc] = useState('');

          const fetchGoals = () => {
              supabase
                    .from('goals')
                          .select('*')
                                .eq('user_id', userId)
                                      .order('created_at', { ascending: false })
                                            .then(({ data }) => setGoals(data || []));
                                              };

                                                useEffect(() => {
                                                    fetchGoals();
                                                      }, [userId]);

                                                        const addGoal = async () => {
                                                            if (!title.trim()) return;
                                                                await supabase.from('goals').insert({ user_id: userId, title, description: desc }).select().single();
                                                                    setTitle('');
                                                                        setDesc('');
                                                                            fetchGoals();
                                                                              };

                                                                                const updateProgress = async (id: string, progress: number) => {
                                                                                    await supabase.from('goals').update({ progress: Math.min(progress + 10, 100) }).eq('id', id);
                                                                                        setGoals(prev => prev.map(g => g.id === id ? { ...g, progress: Math.min(g.progress + 10, 100) } : g));
                                                                                          };

                                                                                            return (
                                                                                                <View style={styles.container}>
                                                                                                      <Text style={styles.header}>🎯 أهدافي</Text>
                                                                                                            <View style={styles.inputRow}>
                                                                                                                    <TextInput
                                                                                                                              style={styles.input}
                                                                                                                                        placeholder="هدف جديد"
                                                                                                                                                  placeholderTextColor="#8B7BA3"
                                                                                                                                                            value={title}
                                                                                                                                                                      onChangeText={setTitle}
                                                                                                                                                                              />
                                                                                                                                                                                      <TextInput
                                                                                                                                                                                                style={styles.input}
                                                                                                                                                                                                          placeholder="وصف (اختياري)"
                                                                                                                                                                                                                    placeholderTextColor="#8B7BA3"
                                                                                                                                                                                                                              value={desc}
                                                                                                                                                                                                                                        onChangeText={setDesc}
                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                        <TouchableOpacity style={styles.addBtn} onPress={addGoal}>
                                                                                                                                                                                                                                                                  <Text style={{ color: '#FFF', fontWeight: 'bold' }}>+</Text>
                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                      <FlatList
                                                                                                                                                                                                                                                                                              data={goals}
                                                                                                                                                                                                                                                                                                      keyExtractor={item => item.id}
                                                                                                                                                                                                                                                                                                              renderItem={({ item }) => (
                                                                                                                                                                                                                                                                                                                        <View style={styles.goal}>
                                                                                                                                                                                                                                                                                                                                    <Text style={styles.goalTitle}>{item.title}</Text>
                                                                                                                                                                                                                                                                                                                                                {item.description ? <Text style={styles.desc}>{item.description}</Text> : null}
                                                                                                                                                                                                                                                                                                                                                            <View style={styles.progressBar}>
                                                                                                                                                                                                                                                                                                                                                                          <View style={[styles.progressFill, { width: `${item.progress}%` }]} />
                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.progressText}>{item.progress}%</Text>
                                                                                                                                                                                                                                                                                                                                                                                                              {!item.completed && (
                                                                                                                                                                                                                                                                                                                                                                                                                            <TouchableOpacity style={styles.updateBtn} onPress={() => updateProgress(item.id, item.progress)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <Text style={{ color: '#E0AAFF' }}>تحديث +10%</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      container: { flex: 1, backgroundColor: '#0F0A1A', padding: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        header: { fontSize: 22, fontWeight: '700', color: '#FFF', marginBottom: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          inputRow: { flexDirection: 'row', marginBottom: 16, gap: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            input: { flex: 1, backgroundColor: '#1A1226', color: '#FFF', padding: 10, borderRadius: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              addBtn: { backgroundColor: '#E0AAFF', width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                goal: { backgroundColor: '#1A1226', padding: 12, borderRadius: 10, marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  goalTitle: { color: '#FFF', fontWeight: '600', fontSize: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    desc: { color: '#8B7BA3', marginTop: 4 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      progressBar: { height: 6, backgroundColor: '#2D1B4D', borderRadius: 3, marginTop: 8, overflow: 'hidden' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        progressFill: { height: '100%', backgroundColor: '#E0AAFF' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          progressText: { color: '#D0B4E0', fontSize: 12, marginTop: 4 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updateBtn: { marginTop: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            