import { View, Text, TouchableOpacity, StyleSheet, ScrollView, Switch, Alert, Linking } from 'react-native';
import { router } from 'expo-router';
import { useTwinStore } from '../store/useTwinStore';
import { supabase } from '../lib/supabase';
import { API } from '../lib/api';

export default function Settings() {
  const { tier, calmMode, toggleCalmMode, userId } = useTwinStore();

    const logout = async () => {
        await supabase.auth.signOut();
            router.replace('/');
              };

                const deleteAccount = () => {
                    Alert.alert(
                          'حذف نهائي',
                                'لا يمكن التراجع. سيتم حذف جميع ذكرياتك وبياناتك نهائياً.',
                                      [
                                              { text: 'إلغاء' },
                                                      {
                                                                text: 'حذف',
                                                                          style: 'destructive',
                                                                                    onPress: async () => {
                                                                                                await API.delete('/api/account');
                                                                                                            await supabase.auth.signOut();
                                                                                                                        router.replace('/');
                                                                                                                                  },
                                                                                                                                          },
                                                                                                                                                ]
                                                                                                                                                    );
                                                                                                                                                      };

                                                                                                                                                        return (
                                                                                                                                                            <ScrollView style={styles.container}>
                                                                                                                                                                  <View style={styles.card}>
                                                                                                                                                                          <Text style={styles.title}>الإعدادات</Text>
                                                                                                                                                                                  <Text style={styles.tier}>الخطة الحالية: {tier}</Text>

                                                                                                                                                                                          <View style={styles.row}>
                                                                                                                                                                                                    <Text style={styles.label}>🕊️ وضع الهدوء</Text>
                                                                                                                                                                                                              <Switch
                                                                                                                                                                                                                          value={calmMode}
                                                                                                                                                                                                                                      onValueChange={toggleCalmMode}
                                                                                                                                                                                                                                                  trackColor={{ false: '#333', true: '#E0AAFF' }}
                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                    </View>

                                                                                                                                                                                                                                                                            <TouchableOpacity style={styles.button} onPress={() => router.push('/subscription')}>
                                                                                                                                                                                                                                                                                      <Text style={styles.buttonText}>💎 ترقية الخطة</Text>
                                                                                                                                                                                                                                                                                              </TouchableOpacity>

                                                                                                                                                                                                                                                                                                      <TouchableOpacity style={styles.button} onPress={() => router.push('/goals')}>
                                                                                                                                                                                                                                                                                                                <Text style={styles.buttonText}>🎯 أهدافي</Text>
                                                                                                                                                                                                                                                                                                                        </TouchableOpacity>

                                                                                                                                                                                                                                                                                                                                <TouchableOpacity style={styles.button} onPress={() => Linking.openURL('https://findahelpline.com')}>
                                                                                                                                                                                                                                                                                                                                          <Text style={styles.buttonText}>🆘 دعم طوارئ نفسي</Text>
                                                                                                                                                                                                                                                                                                                                                  </TouchableOpacity>

                                                                                                                                                                                                                                                                                                                                                          <TouchableOpacity style={[styles.button, styles.logoutBtn]} onPress={logout}>
                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.buttonText}>تسجيل الخروج</Text>
                                                                                                                                                                                                                                                                                                                                                                            </TouchableOpacity>

                                                                                                                                                                                                                                                                                                                                                                                    <TouchableOpacity style={[styles.button, styles.dangerBtn]} onPress={deleteAccount}>
                                                                                                                                                                                                                                                                                                                                                                                              <Text style={styles.buttonText}>🗑️ حذف الحساب نهائياً</Text>
                                                                                                                                                                                                                                                                                                                                                                                                      </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                                                                </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                  const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                    container: { flex: 1, backgroundColor: '#0F0A1A' },
                                                                                                                                                                                                                                                                                                                                                                                                                      card: { padding: 20, gap: 14 },
                                                                                                                                                                                                                                                                                                                                                                                                                        title: { color: '#FFF', fontSize: 20, fontWeight: '700', marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                          tier: { color: '#E0AAFF', fontSize: 16, marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                            row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#1A1226', padding: 12, borderRadius: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                              label: { color: '#FFF' },
                                                                                                                                                                                                                                                                                                                                                                                                                                button: { backgroundColor: '#1A1226', padding: 14, borderRadius: 10, alignItems: 'center', borderWidth: 1, borderColor: '#3A2A5D' },
                                                                                                                                                                                                                                                                                                                                                                                                                                  buttonText: { color: '#FFF', fontWeight: '600' },
                                                                                                                                                                                                                                                                                                                                                                                                                                    logoutBtn: { borderColor: '#E0AAFF' },
                                                                                                                                                                                                                                                                                                                                                                                                                                      dangerBtn: { borderColor: '#FF6B6B' },
                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                      