import { View, Text, FlatList, StyleSheet } from 'react-native';
import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useTwinStore } from '../store/useTwinStore';

export default function Timeline() {
  const { userId } = useTwinStore();
    const [memories, setMemories] = useState<any[]>([]);
      const [loading, setLoading] = useState(true);

        useEffect(() => {
            if (!userId) return;
                supabase
                      .from('memories')
                            .select('content, created_at, emotional_tag, importance_score')
                                  .eq('user_id', userId)
                                        .order('created_at', { ascending: false })
                                              .limit(50)
                                                    .then(({ data }) => {
                                                            setMemories(data || []);
                                                                    setLoading(false);
                                                                          });
                                                                            }, [userId]);

                                                                              return (
                                                                                  <FlatList
                                                                                        style={styles.container}
                                                                                              data={memories}
                                                                                                    keyExtractor={item => item.id}
                                                                                                          ListHeaderComponent={<Text style={styles.header}>📅 خط الذكريات</Text>}
                                                                                                                ListEmptyComponent={
                                                                                                                        loading
                                                                                                                                  ? <Text style={styles.empty}>تحميل...</Text>
                                                                                                                                            : <Text style={styles.empty}>لا توجد ذكريات بعد.</Text>
                                                                                                                                                  }
                                                                                                                                                        renderItem={({ item }) => (
                                                                                                                                                                <View style={styles.item}>
                                                                                                                                                                          <View style={styles.tagRow}>
                                                                                                                                                                                      {item.emotional_tag && (
                                                                                                                                                                                                    <View style={styles.tag}>
                                                                                                                                                                                                                    <Text style={styles.tagText}>{item.emotional_tag}</Text>
                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                          <Text style={styles.date}>
                                                                                                                                                                                                                                                                        {new Date(item.created_at).toLocaleDateString('ar-EG', {
                                                                                                                                                                                                                                                                                        year: 'numeric',
                                                                                                                                                                                                                                                                                                        month: 'short',
                                                                                                                                                                                                                                                                                                                        day: 'numeric',
                                                                                                                                                                                                                                                                                                                                      })}
                                                                                                                                                                                                                                                                                                                                                  </Text>
                                                                                                                                                                                                                                                                                                                                                            </View>
                                                                                                                                                                                                                                                                                                                                                                      <Text style={styles.content}>{item.content}</Text>
                                                                                                                                                                                                                                                                                                                                                                                {item.importance_score > 0.7 && <Text style={styles.star}>⭐ ذكرى مهمة</Text>}
                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                    contentContainerStyle={{ paddingBottom: 20 }}
                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                          const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                            container: { flex: 1, backgroundColor: '#0F0A1A', paddingHorizontal: 16, paddingTop: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                              header: { fontSize: 20, fontWeight: '700', color: '#FFF', marginBottom: 16 },
                                                                                                                                                                                                                                                                                                                                                                                                                item: { padding: 14, borderBottomWidth: 1, borderColor: '#1A1226', marginBottom: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                  tagRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6, gap: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                    tag: { backgroundColor: '#2D1B4D', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                      tagText: { color: '#E0AAFF', fontSize: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                        date: { color: '#8B7BA3', fontSize: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                          content: { color: '#FFF', fontSize: 14, lineHeight: 20, marginBottom: 4 },
                                                                                                                                                                                                                                                                                                                                                                                                                            star: { color: '#FFD93D', fontSize: 11 },
                                                                                                                                                                                                                                                                                                                                                                                                                              empty: { color: '#8B7BA3', textAlign: 'center', marginTop: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                              